#!/bin/sh

echo "react
react-dom
babel-core
babel-eslint
babel-plugin-transform-object-rest-spread
babel-preset-flow
babel-preset-react
cssnano
eslint
eslint-config-airbnb
eslint-config-prettier
eslint-loader
eslint-plugin-flowtype
eslint-plugin-import
eslint-plugin-jsx-a11y
eslint-plugin-react
flow-bin
parcel-bundler
stylelint-config-standard" |
    while read -r package; do
        filename="testfiles/npm/$package.json"
        [ ! -f "$filename" ] && echo "npm - $package" && curl -L# "https://registry.npmjs.org/$package" >"$filename"
    done

echo "clap
version_check
time
ansi_term
libc
term_grid
terminal_size
time
chrono-humanize
unicode-width
lscolors
wild
globset
xdg
yaml-rust
users
winapi
assert_cmd
assert_fs
predicates
tempfile" |
    while read -r package; do
        filename="testfiles/cargo/$package.json"
        [ ! -f "$filename" ] && echo "cargo - $package" && curl -L# "https://crates.io/api/v1/crates/$package" >"$filename"
    done
